import pandas as pd
from app.services.analytics_service import AnalyticsService

class AnalyticsEngine(AnalyticsService):
    """
    Executes dynamic Pandas queries based on the JSON plan generated by the LLM.
    """

    def __init__(self):
        super().__init__()

    def _match_col(self, df, col_name):
        if not col_name: return None
        if isinstance(col_name, list):
            return [self._match_col(df, c) for c in col_name]
        if col_name in df.columns: return col_name
        
        normalized_col = str(col_name).strip().lower().replace(" ", "_").replace("%", "percent").replace("/", "_")
        if normalized_col in df.columns:
            return normalized_col
            
        for c in df.columns:
            if c.lower().strip() == str(col_name).lower().strip():
                return c
        return col_name

    def execute(self, plan: dict):
        # Handle out of domain questions
        if plan.get("error") == "out_of_domain":
            return "OUT_OF_DOMAIN"

        # Handle dashboard / summary request
        if plan.get("dashboard") is True:
            return self._get_dashboard()

        try:
            df_view = self.df.copy()

            # 1. Apply Filters
            filters = plan.get("filters", [])
            if isinstance(filters, list):
                for f in filters:
                    col = self._match_col(df_view, f.get("column"))
                    op = f.get("operator")
                    val = f.get("value")
                    if col and op and val is not None:
                        if op == "==":
                            df_view = df_view[df_view[col] == val]
                        elif op == "!=":
                            df_view = df_view[df_view[col] != val]
                        elif op == ">":
                            df_view = df_view[df_view[col] > val]
                        elif op == "<":
                            df_view = df_view[df_view[col] < val]
                        elif op == ">=":
                            df_view = df_view[df_view[col] >= val]
                        elif op == "<=":
                            df_view = df_view[df_view[col] <= val]

            # 2. Apply Group By & Aggregation
            group_by = self._match_col(df_view, plan.get("group_by"))
            agg_column = self._match_col(df_view, plan.get("agg_column"))
            agg_method = plan.get("agg_method")

            if group_by and agg_column and agg_method:
                # E.g. groupby(['City'])['Sales'].sum()
                result = df_view.groupby(group_by)[agg_column].agg(agg_method)
                
                # Sort the results descending for better readability
                if isinstance(result, pd.Series) or isinstance(result, pd.DataFrame):
                    result = result.sort_values(ascending=False)
                    
            elif agg_column and agg_method:
                # Global aggregation without grouping (e.g. total sales)
                result = df_view[agg_column].agg(agg_method)
            else:
                # If no aggregation requested, just return top rows or summary
                result = df_view.head(10)

            return result

        except Exception as e:
            return f"Error executing query: {str(e)}"

    def _get_dashboard(self):
        """Generates a comprehensive snapshot of the dataset."""
        return {
            "Total Sales": self.df["sales"].sum(),
            "Average Sale": self.df["sales"].mean(),
            "Total Transactions": len(self.df),
            "Average Rating": self.df["rating"].mean(),
            "Best Product Line": self.df.groupby("product_line")["sales"].sum().idxmax(),
            "Best Branch": self.df.groupby("branch")["sales"].sum().idxmax(),
            "Best City": self.df.groupby("city")["sales"].sum().idxmax(),
            "Preferred Payment": self.df["payment"].value_counts().idxmax(),
        }