import pandas as pd
from app.services.analytics_service import AnalyticsService

class AnalyticsEngine(AnalyticsService):
    """
    Executes dynamic Pandas queries based on the JSON plan generated by the LLM.
    """

    def __init__(self):
        super().__init__()

    def _match_col(self, df, col_name):
        if not col_name: return None
        if isinstance(col_name, list):
            return [self._match_col(df, c) for c in col_name]
        if col_name in df.columns: return col_name
        
        normalized_col = str(col_name).strip().lower().replace(" ", "_").replace("%", "percent").replace("/", "_")
        if normalized_col in df.columns:
            return normalized_col
            
        for c in df.columns:
            if c.lower().strip() == str(col_name).lower().strip():
                return c
        return col_name

    def execute(self, plan: dict):
        # Handle out of domain questions
        if plan.get("error") == "out_of_domain":
            return "OUT_OF_DOMAIN"

        # Handle dashboard / summary request
        if plan.get("dashboard") is True:
            return self._get_dashboard()

        try:
            df_view = self.df.copy()

            # 1. Apply Filters
            filters = plan.get("filters", [])
            if isinstance(filters, list):
                for f in filters:
                    col = self._match_col(df_view, f.get("column"))
                    op = f.get("operator")
                    val = f.get("value")
                    if col and op and val is not None:
                        if op == "==":
                            df_view = df_view[df_view[col] == val]
                        elif op == "!=":
                            df_view = df_view[df_view[col] != val]
                        elif op == ">":
                            df_view = df_view[df_view[col] > val]
                        elif op == "<":
                            df_view = df_view[df_view[col] < val]
                        elif op == ">=":
                            df_view = df_view[df_view[col] >= val]
                        elif op == "<=":
                            df_view = df_view[df_view[col] <= val]

            # 2. Apply Group By & Aggregation
            group_by = self._match_col(df_view, plan.get("group_by"))
            agg_column = self._match_col(df_view, plan.get("agg_column"))
            agg_method = plan.get("agg_method")

            if agg_method:
                agg_method = str(agg_method).lower().strip()
                if agg_method in ["avg", "average"]:
                    agg_method = "mean"

            if group_by and agg_column and agg_method:
                # E.g. groupby(['City'])['Sales'].sum()
                result = df_view.groupby(group_by)[agg_column].agg(agg_method)
                
                # Sort the results descending for better readability
                if isinstance(result, pd.Series):
                    result = result.sort_values(ascending=False).head(20)
                elif isinstance(result, pd.DataFrame):
                    # For dataframes, sort by the first column
                    sort_col = result.columns[0]
                    result = result.sort_values(by=sort_col, ascending=False).head(20)
                    
            elif agg_column and agg_method:
                # Global aggregation without grouping (e.g. total sales)
                result = df_view[agg_column].agg(agg_method)
                if isinstance(result, pd.Series) or isinstance(result, pd.DataFrame):
                    result = result.head(20)
            else:
                # If no aggregation requested, just return top rows or summary
                result = df_view.head(20)

            return result

        except Exception as e:
            return f"Error executing query: {str(e)}"

    def _get_dashboard(self):
        """Generates a comprehensive snapshot of the SaaS dataset."""
        active_customers = self.df[self.df["churned"] == 0]
        return {
            "Total Active MRR": active_customers["mrr"].sum().round(2),
            "Overall Churn Rate (%)": (self.df["churned"].mean() * 100).round(2),
            "Total Customers": len(self.df),
            "Average CAC": self.df["cac"].mean().round(2),
            "Top Acquisition Channel (by Volume)": self.df["acquisition_channel"].value_counts().idxmax(),
            "Most Profitable Industry (Total MRR)": self.df.groupby("industry")["mrr"].sum().idxmax(),
            "Average Support Tickets": self.df["support_tickets"].mean().round(2),
            "Average Tenure (Months)": self.df["tenure_months"].mean().round(2),
        }